import json
from pathlib import Path

import pytest

from crypto_validation.cli import EXIT_OK, EXIT_VALIDATION_FAIL, main


# Representative CAVS CBC vectors copied from the user-provided known-good data.
# These are intentionally hardcoded test fixtures, not generated by the
# framework, so they can detect regressions in parsing, DUT execution, and
# comparison behavior.
CAVS_CBC_GFSBOX_SUBSET = """# CAVS 11.1
# AESVS GFSbox test data for CBC
# State : Encrypt and Decrypt

[ENCRYPT]

COUNT = 0
KEY = 00000000000000000000000000000000
IV = 00000000000000000000000000000000
PLAINTEXT = f34481ec3cc627bacd5dc3fb08f273e6
CIPHERTEXT = 0336763e966d92595a567cc9ce537f5e

COUNT = 1
KEY = 00000000000000000000000000000000
IV = 00000000000000000000000000000000
PLAINTEXT = 9798c4640bad75c7c3227db910174e72
CIPHERTEXT = a9a1631bf4996954ebc093957b234589

COUNT = 2
KEY = 000000000000000000000000000000000000000000000000
IV = 00000000000000000000000000000000
PLAINTEXT = 1b077a6af4b7f98229de786d7516b639
CIPHERTEXT = 275cfc0413d8ccb70513c3859b1d0f72

COUNT = 3
KEY = 000000000000000000000000000000000000000000000000
IV = 00000000000000000000000000000000
PLAINTEXT = 9c2d8842e5f48f57648205d39a239af1
CIPHERTEXT = c9b8135ff1b5adc413dfd053b21bd96d

COUNT = 4
KEY = 0000000000000000000000000000000000000000000000000000000000000000
IV = 00000000000000000000000000000000
PLAINTEXT = 014730f80ac625fe84f026c60bfd547d
CIPHERTEXT = 5c9d844ed46f9885085e5d6a4f94c7d7

COUNT = 5
KEY = 0000000000000000000000000000000000000000000000000000000000000000
IV = 00000000000000000000000000000000
PLAINTEXT = 0b24af36193ce4665f2825d7b4749c98
CIPHERTEXT = a9ff75bd7cf6613d3731c77c3b6d0c04

[DECRYPT]

COUNT = 0
KEY = 00000000000000000000000000000000
IV = 00000000000000000000000000000000
CIPHERTEXT = 0336763e966d92595a567cc9ce537f5e
PLAINTEXT = f34481ec3cc627bacd5dc3fb08f273e6

COUNT = 1
KEY = 00000000000000000000000000000000
IV = 00000000000000000000000000000000
CIPHERTEXT = a9a1631bf4996954ebc093957b234589
PLAINTEXT = 9798c4640bad75c7c3227db910174e72

COUNT = 2
KEY = 000000000000000000000000000000000000000000000000
IV = 00000000000000000000000000000000
CIPHERTEXT = 275cfc0413d8ccb70513c3859b1d0f72
PLAINTEXT = 1b077a6af4b7f98229de786d7516b639

COUNT = 3
KEY = 000000000000000000000000000000000000000000000000
IV = 00000000000000000000000000000000
CIPHERTEXT = c9b8135ff1b5adc413dfd053b21bd96d
PLAINTEXT = 9c2d8842e5f48f57648205d39a239af1

COUNT = 4
KEY = 0000000000000000000000000000000000000000000000000000000000000000
IV = 00000000000000000000000000000000
CIPHERTEXT = 5c9d844ed46f9885085e5d6a4f94c7d7
PLAINTEXT = 014730f80ac625fe84f026c60bfd547d

COUNT = 5
KEY = 0000000000000000000000000000000000000000000000000000000000000000
IV = 00000000000000000000000000000000
CIPHERTEXT = a9ff75bd7cf6613d3731c77c3b6d0c04
PLAINTEXT = 0b24af36193ce4665f2825d7b4749c98
"""


# Representative CAVS ECB VarKey vectors copied from the user-provided
# known-good data.
CAVS_ECB_VARKEY_256_SUBSET = """# CAVS 11.1
# AESVS VarKey test data for ECB
# State : Encrypt and Decrypt
# Key Length : 256

[ENCRYPT]

COUNT = 0
KEY = 8000000000000000000000000000000000000000000000000000000000000000
PLAINTEXT = 00000000000000000000000000000000
CIPHERTEXT = e35a6dcb19b201a01ebcfa8aa22b5759

COUNT = 1
KEY = c000000000000000000000000000000000000000000000000000000000000000
PLAINTEXT = 00000000000000000000000000000000
CIPHERTEXT = b29169cdcf2d83e838125a12ee6aa400

COUNT = 2
KEY = e000000000000000000000000000000000000000000000000000000000000000
PLAINTEXT = 00000000000000000000000000000000
CIPHERTEXT = d8f3a72fc3cdf74dfaf6c3e6b97b2fa6

[DECRYPT]

COUNT = 0
KEY = 8000000000000000000000000000000000000000000000000000000000000000
CIPHERTEXT = e35a6dcb19b201a01ebcfa8aa22b5759
PLAINTEXT = 00000000000000000000000000000000

COUNT = 1
KEY = c000000000000000000000000000000000000000000000000000000000000000
CIPHERTEXT = b29169cdcf2d83e838125a12ee6aa400
PLAINTEXT = 00000000000000000000000000000000

COUNT = 2
KEY = e000000000000000000000000000000000000000000000000000000000000000
CIPHERTEXT = d8f3a72fc3cdf74dfaf6c3e6b97b2fa6
PLAINTEXT = 00000000000000000000000000000000
"""


# NIST SP 800-38A Appendix F.5 AES-CTR vectors, including a partial-block case
# that uses the first eight bytes of the first ciphertext block.
SP800_38A_CTR_SUBSET = """# NIST SP 800-38A Appendix F.5 style AES-CTR vectors

[ENCRYPT]

COUNT = 0
KEY = 2b7e151628aed2a6abf7158809cf4f3c
IV = f0f1f2f3f4f5f6f7f8f9fafbfcfdfeff
PLAINTEXT = 6bc1bee22e409f96e93d7e117393172a
CIPHERTEXT = 874d6191b620e3261bef6864990db6ce

COUNT = 1
KEY = 2b7e151628aed2a6abf7158809cf4f3c
IV = f0f1f2f3f4f5f6f7f8f9fafbfcfdfeff
PLAINTEXT = 6bc1bee22e409f96
CIPHERTEXT = 874d6191b620e326

[DECRYPT]

COUNT = 0
KEY = 2b7e151628aed2a6abf7158809cf4f3c
IV = f0f1f2f3f4f5f6f7f8f9fafbfcfdfeff
CIPHERTEXT = 874d6191b620e3261bef6864990db6ce
PLAINTEXT = 6bc1bee22e409f96e93d7e117393172a

COUNT = 1
KEY = 2b7e151628aed2a6abf7158809cf4f3c
IV = f0f1f2f3f4f5f6f7f8f9fafbfcfdfeff
CIPHERTEXT = 874d6191b620e326
PLAINTEXT = 6bc1bee22e409f96
"""


def _write_vector(tmp_path: Path, filename: str, content: str) -> Path:
    path = tmp_path / filename
    path.write_text(content, encoding="utf-8")
    return path


def _run_vector(tmp_path: Path, mode: str, operation: str, vector_path: Path) -> tuple[int, dict]:
    exit_code = main(
        [
            "--algorithm",
            "AES",
            "--mode",
            mode,
            "--operation",
            operation,
            "--test-type",
            "KAT",
            "--vector-file",
            str(vector_path),
            "--dut",
            "python",
            "--report-format",
            "json",
            "--report-dir",
            str(tmp_path / "reports"),
        ]
    )
    reports = sorted((tmp_path / "reports").glob("*.json"))
    payload = json.loads(reports[-1].read_text(encoding="utf-8")) if reports else {}
    return exit_code, payload


@pytest.mark.parametrize(
    ("mode", "operation", "filename", "content", "expected_total"),
    [
        ("CBC", "encrypt", "cavs_cbc_gfsbox.rsp", CAVS_CBC_GFSBOX_SUBSET, 6),
        ("CBC", "decrypt", "cavs_cbc_gfsbox.rsp", CAVS_CBC_GFSBOX_SUBSET, 6),
        ("ECB", "encrypt", "cavs_ecb_varkey256.rsp", CAVS_ECB_VARKEY_256_SUBSET, 3),
        ("ECB", "decrypt", "cavs_ecb_varkey256.rsp", CAVS_ECB_VARKEY_256_SUBSET, 3),
        ("CTR", "encrypt", "sp800_38a_ctr.rsp", SP800_38A_CTR_SUBSET, 2),
        ("CTR", "decrypt", "sp800_38a_ctr.rsp", SP800_38A_CTR_SUBSET, 2),
    ],
)
def test_known_good_vectors_pass(tmp_path, mode, operation, filename, content, expected_total):
    vector_path = _write_vector(tmp_path, filename, content)

    exit_code, payload = _run_vector(tmp_path, mode, operation, vector_path)

    assert exit_code == EXIT_OK
    assert payload["summary"]["total"] == expected_total
    assert payload["summary"]["passed"] == expected_total
    assert payload["summary"]["validation_failed"] == 0


@pytest.mark.parametrize(
    ("mode", "operation", "filename", "content"),
    [
        (
            "CBC",
            "encrypt",
            "cavs_cbc_gfsbox_bad_encrypt.rsp",
            CAVS_CBC_GFSBOX_SUBSET.replace(
                "0336763e966d92595a567cc9ce537f5e",
                "1336763e966d92595a567cc9ce537f5e",
                1,
            ),
        ),
        (
            "CBC",
            "decrypt",
            "cavs_cbc_gfsbox_bad_decrypt.rsp",
            CAVS_CBC_GFSBOX_SUBSET.replace(
                "f34481ec3cc627bacd5dc3fb08f273e6",
                "e34481ec3cc627bacd5dc3fb08f273e6",
                2,
            ),
        ),
        (
            "ECB",
            "encrypt",
            "cavs_ecb_bad_encrypt.rsp",
            CAVS_ECB_VARKEY_256_SUBSET.replace(
                "e35a6dcb19b201a01ebcfa8aa22b5759",
                "f35a6dcb19b201a01ebcfa8aa22b5759",
                1,
            ),
        ),
        (
            "ECB",
            "decrypt",
            "cavs_ecb_bad_decrypt.rsp",
            CAVS_ECB_VARKEY_256_SUBSET.replace(
                "00000000000000000000000000000000",
                "10000000000000000000000000000000",
                7,
            ),
        ),
        (
            "CTR",
            "encrypt",
            "sp800_38a_bad_ctr_encrypt.rsp",
            SP800_38A_CTR_SUBSET.replace(
                "874d6191b620e3261bef6864990db6ce",
                "974d6191b620e3261bef6864990db6ce",
                1,
            ),
        ),
        (
            "CTR",
            "decrypt",
            "sp800_38a_bad_ctr_decrypt.rsp",
            SP800_38A_CTR_SUBSET.replace(
                "6bc1bee22e409f96e93d7e117393172a",
                "7bc1bee22e409f96e93d7e117393172a",
                2,
            ),
        ),
    ],
)
def test_random_manual_failure_injections_are_detected(tmp_path, mode, operation, filename, content):
    vector_path = _write_vector(tmp_path, filename, content)

    exit_code, payload = _run_vector(tmp_path, mode, operation, vector_path)

    assert exit_code == EXIT_VALIDATION_FAIL
    assert payload["summary"]["validation_failed"] >= 1
    failing_results = [result for result in payload["results"] if result["status"] == "VALIDATION_FAIL"]
    assert failing_results
    assert failing_results[0]["mismatches"]


@pytest.mark.parametrize(
    ("filename", "content"),
    [
        (
            "sp800_38a_ctr_bad_key.rsp",
            SP800_38A_CTR_SUBSET.replace(
                "2b7e151628aed2a6abf7158809cf4f3c",
                "3b7e151628aed2a6abf7158809cf4f3c",
                1,
            ),
        ),
        (
            "sp800_38a_ctr_bad_counter.rsp",
            SP800_38A_CTR_SUBSET.replace(
                "f0f1f2f3f4f5f6f7f8f9fafbfcfdfeff",
                "e0f1f2f3f4f5f6f7f8f9fafbfcfdfeff",
                1,
            ),
        ),
    ],
)
def test_ctr_failure_injection_with_modified_input_fields_is_detected(tmp_path, filename, content):
    vector_path = _write_vector(tmp_path, filename, content)

    exit_code, payload = _run_vector(tmp_path, "CTR", "encrypt", vector_path)

    assert exit_code == EXIT_VALIDATION_FAIL
    assert payload["summary"]["validation_failed"] >= 1
